version: '3'
services:
  bookingservice:
    build: BookingService/
    image: cinema/bookingservice:latest
    depends_on: 
      - theatreservice
    ports:
     - "8081:8080"
  movieservice:
    build: MovieService/
    image: cinema/movieservice:latest
    ports:
     - "8082:8080"
  theatreservice:
    build: TheatreService/
    image: cinema/theatreservice:latest
    depends_on: 
      - movieservice
    ports:
     - "8083:8080"
  frontend: 
    build: WebUI/
    image: cinema/frontend:latest
    ports:
     - "80:80"