version: '3'
services:
  bookingservice:
    image: cinema/bookingservice:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 350M
    ports:
     - "8081:8080"
    networks:
    - webnet
  movieservice:
    image: cinema/movieservice:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 350M
    ports:
     - "8082:8080"
    networks:
    - webnet
  theatreservice:
    image: cinema/theatreservice:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 350M
    ports:
     - "8083:8080"
    networks:
    - webnet
  frontend:
    image: cinema/frontend:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 100M
    ports:
     - "80:80"
    networks:
    - webnet
networks:
  webnet: