version: '3'
services:
  bookingservice:
    build: 
      context: BookingService/
    depends_on: 
      - theatreservice
    ports:
     - "8081:8080"
  movieservice:
    build:
      context: MovieService/
    ports:
     - "8082:8080"
  theatreservice:
    build:
      context: TheatreService/
    depends_on: 
      - movieservice
    ports:
     - "8083:8080"
  frontend:
    build:
      context: WebUI/
    ports:
     - "80:80"